import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Common/Navbar";
import Footer from "@/components/Common/Footer";
import Copyright from "@/components/Common/Copyright";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans bg-primary-white min-h-[100dvh]  text-text-color-black *:px-center grid grid-rows-[auto_1fr_auto_auto] `}
      >
        <Navbar />
        <hr />
        <main className="min-h-[calc(100vh-10rem)] ">
          {children}
        </main>
        <Footer />
        <hr />
        <Copyright />
      </body>
    </html>
  );
}
